### ISSUE TITLE
Issue w/ StickerMule?

### ISSUE THREAD

**Issue by jananiravi** [rladies/branding-materials#1]
Hi all, it seems like there's an unresolved issue with StickerMule (see 🧵 on [R-Ladies slack](https://r-ladies.slack.com/archives/CCWALA0B1/p1678494264989859) w/ @yabellini). 

There were some alternatives posted in response to the [original post](https://r-ladies.slack.com/archives/C02FJ4U6F/p1678398926483209) by @AndreaSanchezTapia & @hturner.

- [RedBubble](https://www.redbubble.com/shop/stickers) (straightforward for hex stickers & custom designs?)
- http://moo.com/
- https://treehousestickers.com/
- https://stickerit.co/
- https://stickerapp.com (?)
- https://www.makestickers.com/

**Comment by cosimameyer** [comment]
Thanks for bringing it up! I also came across the guidelines [here](https://github.com/rladies/branding-materials/tree/main/stickers) and wanted to open an issue on it. I believe some PyLadies are using stickerapp.com (also available in other countries than the US). 

FYI: @rladies/leadership

**Comment by yabellini** [comment]
I remove mentions to stiker mule and add this option to the readme.
